require:
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.1.2
Metrics/AbcSize:
  Max: 40
Layout/LineLength:
  Max: 300
RSpec/ExampleLength:
  Max: 40